[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build" 